[[redirects]]
     from = "/currency"
     to = "https://api.mytokenapi.com/currency/"
     status = 200
     force = true # COMMENT: ensure that we always redirect
     headers = {X-From = "Netlify"}

[[headers]]
    for="/*"
    [headers.values]
    Acces-Control-Allow-Origin="*"
