[[redirects]]
     from = "/api/try/ajax/"
     to = "https://www.runoob.com/try/ajax/"
     status = 200
     force = true # COMMENT: ensure that we always redirect
     headers = {X-From = "Netlify"}

[[headers]]
    for="/*"
    [headers.values]
    Acces-Control-Allow-Origin="*"
